### ISSUE TITLE
Feature request(s).

### ISSUE THREAD

**Issue by miusaky** [Le0xFF/VoidLinuxInstaller#1]
Your script is wonderful. Takes a lot of hassle out of the installation process. Thanks for sharing it.

If you're looking to expand the script, I think there are a few features which would be useful.

- Make encryption optional. 
- Add support for different boot options e.g. [EFISTUB](https://wiki.archlinux.org/title/EFISTUB). I have step-by-step instructions for how to set this up on Void towards the bottom of [this](https://github.com/miusaky/vl) repository.
- Option to add nonfree + multilib repositories during the installation process.
- Option to install additional packages e.g. nvim during the installation process. 
- Option to clone and configure [void-packages](https://github.com/void-linux/void-packages) during the installation process.

**Comment by Le0xFF** [comment]
Hey thank you for your suggestions! Let me explain something better about the points you wrote down.

* **Easy to implement**
  - [ ] **Option to add nonfree + multilib repositories during the installation process**: this is the easiest one of course;
  - [ ] **Option to clone and configure void-packages during the installation process**: this can be implemented in the chroot script, almost at the end, I see no problem so far in that.

* **Medium difficulty**
  - [ ] **Option to install additional packages during the installation process**: the script needs to check if each package exists or not. Probably it can be done with `xbps-query`? I have to look deeper in the documentation. Also I have to think on how the user should input each package, probably in a loop with an exit keyword;
  - [ ]  **Add support for different boot options**: I never used anything different from grub so I'll have to study how EFISTUB works and how it should be configured. Thanks for your repo, I'll take a look at that for sure!

* **Hard, long term**
  - [ ]  **Make encryption optional**: this could require a minor script rewrite, because a lot of function are based on the fact that encryption is mandatory.

I'll keep track of my updates in this issue and I'll try to begin with implementation starting from next week, as I'm on vacation right now :smile:

Again thanks for your suggestions and as always, PR are absolutely welcome!

**Comment by Miusaky** [comment]
>  Option to install additional packages during the installation process: the script needs to check if each package exists or not. Probably it can be done with xbps-query? I have to look deeper in the documentation. Also I have to think on how the user should input each package, probably in a loop with an exit keyword;

It can look for packages on the host using either no flag (prints package information) or the -l flag which lists the state of the pkg (e.g. installed, unknown etc). The -R flag can be used to look for a package in the repositories instead. [Documentation](https://man.voidlinux.org/xbps-query.1). 

>  Add support for different boot options: I never used anything different from grub so I'll have to study how EFISTUB works and how it should be configured. Thanks for your repo, I'll take a look at that for sure!

Found [this gist](https://gist.github.com/Dko1905/7c9ce651418e01f7838329dd402e5529), which unlike mine, uses luks, and seems to be a bit better documented, so it is perhaps of better value here. 

I favor efistub because it boots from a cold state to a desktop environment in ~5 seconds. Void comes with a hook to manage efi entries on kernel upgrades which makes maintaining it no more effort than Grub. 

>  Make encryption optional: this could require a minor script rewrite, because a lot of function are based on the fact that encryption is mandatory.

That's too bad. Perhaps still worth considering depending on what you want your script to be. For me, luks on stationary, at-home desktops, adds a lot of extra hassle for no real benefits, whereas on a laptop it is of course invaluable. 

I'll see if I can help with some of these, but of course, pick and choose what you want to implement; if something is a lot of work or of no value to you, then leave it be.

**Comment by Le0xFF** [comment]
Thank you for all the links, I'll take a look at them,

And yes, my setup is 80% laptop, I don't have a desktop right now so that's my main point.  
Probably making encryption optional shouldn't even be that hard, but implementing it is just a little bit tedious in the way I have it in mind. As you can see from the script, my Bash scripting skills are really far away from a pro :smile: 

But I'll try to do my best, it's always fun to learn something new :smile:

**Comment by Le0xFF** [comment]
Finally every suggested features has been implemented, thank you for your ideas!

Script should be working without any issue, but if you find any bugs or hiccups, feel free to open a new issue!
