### ISSUE TITLE
Cannot open /var/swap/swapfile: No such file or directory

### ISSUE THREAD

**Issue by smartsyncing** [Le0xFF/VoidLinuxInstaller#11]
When booting a timeline snapper snapshot from grub, that error appears after attempting to initialise swap, and an emergency shell starts until I run exit.

**Comment by Le0xFF** [comment]
Hello and sorry for late reply!

The one you described was a "non-issue" from my point of view, since as you also said, after typing `exit`, you could boot the snapper snapshot and eventually restore your system, regardless of `swap` partition.

From commit https://github.com/Le0xFF/VoidLinuxInstaller/commit/fededc149050a0536998c3063f1d8a25b88159ef issue should be fixed!
Now a proper and dedicated `@swap` subvolume is created to store swapfile and that subvolume is also mounted at boot (through `/etc/fstab`) if user wants to create a swapfile.
If user doesn't want a swapfile, the subvolume will not be mounted, but `@swap` subvolume will still be present.
I don't think that having and empty unused subvolume will be a big problem! :smile:
