### ISSUE TITLE
Separate home partition with a different filesystem 

### ISSUE THREAD

**Issue by MaZED-UP** [Le0xFF/VoidLinuxInstaller#9]
Hello! First of all, thank you for this amazing program.
I want to propose a new feature which is adding the option to have a separate home partition with even another filesystem other than btrfs.

For example: I think that formatting the root partition with btrfs and the home partition with ext4 is good as the user can backup the system apps with snapshots while having a better chance to recover accidentally deleted files from the home partition thanks to ext4's journaling system.

I hope this suggestion doesn't conflict with ssd/nvme trimming feature or any original goals of the script.

**Comment by Le0xFF** [comment]
Hi and thank you for your suggestions!

Regarding the separate `/home` partition: with the BTRFS filesystem there is no real need to have a physical one, as BTRFS subvolumes act exactly like that and that's what my script does, with all the additional benefits of thefilesystem itself.

Regarding the recovery of deleted files: with the snapshot feature of BTRFS you can do exactly that, by setting a time between two snapshot small enough (1 hour, 30 minutes or as small as you like), so I don't see the need to use EXT4 for that.

So I don't think that I will ever implement your suggested changes, also because the script mostly reflect my own needs, and it was a really nice way to learn some scripting skills :smile: 

You can always make a PR if you want; I know the code is not the best one, but it should be pretty easy to understand :smile:
